// app/src/app/update-form/update-form.component.ts
import { Component, OnInit } from '@angular/core';
import { GameService, GET_FULL_GAME } from '../game.service';
import { Apollo } from 'apollo-angular';
import {  FormGroup } from '@angular/forms';
import { Router, ActivatedRoute, ParamMap } from '@angular/router';

@Component({
  selector: 'update-form',
  templateUrl: './update-form.component.html',
  styleUrls: ['./update-form.component.scss']
})
export class UpdateFormComponent implements OnInit {
  game: any;
  loading = true;
  error: any;
  id: string = '';
  name:any = '';  

  constructor(
    private apollo: Apollo, 
    private gameService: GameService,
    private router: Router,
  ) { }

  async updateGameForm() {
    await this.gameService.updateGame(this.id, this.formGroup.value);
  }

  formGroup: FormGroup = this.gameService.gameForm()
  async ngOnInit(): Promise<void> {

    this.name = this.router.url.slice(8);
    await this.apollo.watchQuery({
      query: GET_FULL_GAME,
      variables: {
        title: this.name,
      },
    }).valueChanges.subscribe(({data, loading, error}: any) => {
      this.game = data.findGameByTitle;
      this.loading = loading;
      this.error = error
      this.id = this.game._id;
      this.formGroup.setValue({
        id: this.game._id, 
        title: this.game.title,
        summary: this.game.summary,
        dev: this.game.information.dev,
        pub: this.game.information.pub,
        date: this.game.information.date,
        rating: this.game.information.rating,
        os: this.game.requirements.os,
        cpu: this.game.requirements.cpu,
        ram: this.game.requirements.ram,
        gpu: this.game.requirements.gpu,
        storage: this.game.requirements.storage
      })
    });
  }
}

<div class="container" *ngIf="game">
    <form class="form" [formGroup]=formGroup>
        <div class="row">
            <div class="row">
                <div class="row">
                    <div class="row">
                        <h4>General: {{name}}</h4>
                    </div>
                    <div class="row">
                        <div class="col-3 p-2">
                            <label htmlFor="id">ID:</label>
                        </div>
                        <div class="col p-2">
                            <input type="text" id="id" name="id" formControlName="id" >
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-3 p-2">
                            <label htmlFor="title">Title:</label>
                        </div>
                        <div class="col p-2">
                            <input type="text" id="title" name="title" formControlName="title" >
                        </div>
                    </div>
                    <div class="row">
                    <div class="col-3 p-2">
                        <label htmlFor="summary">Summary:</label>
                    </div>
                    <div class="col p-2">
                        <textarea id="summary" name="summary" formControlName="summary" > </textarea>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="row">
                    <h4>Info:</h4>
                </div>
                <div class="row">
                    <div class="col-3 p-2">
                        <label htmlFor="dev">Developer:</label>
                    </div>
                    <div class="col p-2">
                        <input type="text" id="dev" name="dev"  formControlName="dev" >
                    </div>
                </div>
                <div class="row">
                    <div class="col-3 p-2">
                        <label htmlFor="pub">Publisher:</label>
                    </div>
                    <div class="col p-2">
                        <input type="text" id="pub" name="pub"  formControlName="pub" >
                    </div>
                </div>
                <div class="row">
                    <div class="col-3 p-2">
                        <label htmlFor="date">Release Date:</label>
                    </div>
                    <div class="col p-2">
                        <input type="date" id="date" name="date" formControlName="date"  >
                    </div>
                </div>
                <div class="row">
                    <div class="col-3 p-2">
                        <label htmlFor="rating">Rating:</label>
                    </div>
                    <div class="col p-2">
                        <input type="text" id="rating" name="rating" formControlName="rating"  >
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="row">
                    <h4>System Requirements:</h4>
                </div>
                <div class="row">
                    <div class="col-3 p-2">
                        <label htmlFor="os">OS:</label>
                    </div>
                    <div class="col p-2">
                        <input type="text" id="os" name="os" formControlName="os"  >
                    </div>
                </div>
                <div class="row">
                    <div class="col-3 p-2">
                        <label htmlFor="cpu">Processor:</label>
                    </div>
                    <div class="col p-2">
                        <input type="text" id="cpu" name="cpu" formControlName="cpu"  >
                    </div>
                </div>
                <div class="row">
                    <div class="col-3 p-2">
                        <label htmlFor="ram">Memory:</label>
                    </div>
                    <div class="col p-2">
                        <input type="text" id="ram" name="ram" formControlName="ram"  >
                    </div>
                </div>
                <div class="row">
                    <div class="col-3 p-2">
                        <label htmlFor="gpu">Graphics:</label>
                    </div>
                    <div class="col p-2">
                        <input type="text" id="gpu" name="gpu" formControlName="gpu"  >
                    </div>
                </div>
                <div class="row">
                    <div class="col-3 p-2">
                        <label htmlFor="storage">Storage:</label>
                    </div>
                    <div class="col p-2">
                        <input type="text" id="storage" name="storage" formControlName="storage"  >
                    </div>
                </div>
                </div>
                <div class="d-flex justify-content-center">
                    <button class="btn btn-secondary" type="submit" (click)="updateGameForm(); formGroup.reset()">Update</button>
                </div>
            </div>
        </div>
    </form>
</div>

// app/src/components/updateForm.tsx
import React, {useState} from "react";
import {APIConnection} from "../functions/apiConnection"
import { useParams } from "react-router-dom";

function UpdateForm() {
    const { title } = useParams();
    const json = APIConnection(5000, title);
    const [inputs, setInputs] = useState({});

    const handleChange = (event) => {    
        const name = event.target.name;
        const value = event.target.value;
        setInputs(values => ({...values, [name]: value}))
    }
    const handleSubmit = (event) => {
        event.preventDefault()

        const url = `http://localhost:5000/update/${title}`
        const requestOptions = {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(inputs)
        }
        fetch(url, requestOptions)
        .then(response => console.log('Submitted successfully'))
        .catch(error => console.log('Form submit error', error))
    };
    return (
        <div className="container">
{            json.map((item) => (
        <form onSubmit={handleSubmit} method="POST" action="./" key={item.id}>
            <div className="row">
                <div className="row">
                    <div className="row">
                        <div className="row">
                            <h4>General:</h4>
                            <hr></hr>
                        </div>
                        <div className="row">
                            <div className="col-3 p-2">
                                <label htmlFor="title">Title:</label>
                            </div>
                            <div className="col p-2">
                                <input type="text" id="title" name="title" value={inputs.title || item.title}/>
                            </div>
                        </div>
                        <div className="row">
                            <div className="col-3 p-2">
                                <label htmlFor="summary">Summary:</label>
                            </div>
                        </div>
                    </div>
                    <div className="col">
                        <div className="row">
                            <h4>Info:</h4>
                            <hr></hr>
                        </div>
                        <div className="row">
                            <div className="col-3 p-2">
                                <label htmlFor="dev">Developer:</label>
                            </div>
                            <div className="col p-2">
                                <input type="text" id="dev" name="dev" value={inputs.dev || item.dev} onChange={handleChange}/>
                            </div>
                        </div>
                        <div className="row">
                            <div className="col-3 p-2">
                                <label htmlFor="pub">Publisher:</label>
                            </div>
                            <div className="col p-2">
                                <input type="text" id="pub" name="pub" value={inputs.pub || item.pub} onChange={handleChange}/>
                            </div>
                        </div>
                        <div className="row">
                            <div className="col-3 p-2">
                                <label htmlFor="date">Release Date:</label>
                            </div>
                            <div className="col p-2">
                                <input type="date" id="date" name="date" value={inputs.date || item.date} onChange={handleChange}/>
                            </div>
                        </div>
                        <div className="row">
                            <div className="col-3 p-2">
                                <label htmlFor="rating">Rating:</label>
                            </div>
                            <div className="col p-2">
                                <input type="text" id="rating" name="rating" value={inputs.rating || item.rating} onChange={handleChange}/>
                            </div>
                        </div>
                    </div>
                    <div className="col">
                        <div className="row">
                            <h4>System Requirements:</h4>
                            <hr></hr>
                        </div>
                        <div className="row">
                            <div className="col-3 p-2">
                                <label htmlFor="os">OS:</label>
                            </div>
                            <div className="col p-2">
                                <input type="text" id="os" name="os" value={inputs.os || item.os} onChange={handleChange}/>
                            </div>
                        </div>
                        <div className="row">
                            <div className="col-3 p-2">
                                <label htmlFor="cpu">Processor:</label>
                            </div>
                            <div className="col p-2">
                                <input type="text" id="cpu" name="cpu" value={inputs.cpu || item.cpu} onChange={handleChange}/>
                            </div>
                        </div>
                        <div className="row">
                            <div className="col-3 p-2">
                                <label htmlFor="ram">Memory:</label>
                            </div>
                            <div className="col p-2">
                                <input type="text" id="ram" name="ram" value={inputs.ram || item.ram} onChange={handleChange}/>
                            </div>
                        </div>
                        <div className="row">
                            <div className="col-3 p-2">
                                <label htmlFor="gpu">Graphics:</label>
                            </div>
                            <div className="col p-2">
                                <input type="text" id="gpu" name="gpu" value={inputs.gpu || item.gpu} onChange={handleChange}/>
                            </div>
                        </div>
                        <div className="row">
                            <div className="col-3 p-2">
                                <label htmlFor="storage">Storage:</label>
                            </div>
                            <div className="col p-2">
                                <input type="text" id="storage" name="storage" value={inputs.storage || item.storage} onChange={handleChange}/>
                            </div>
                        </div>
                    </div>
                    <div className="d-flex justify-content-center">
                        <button type="submit" className="btn btn-primary" value="Submit">Update</button>
                    </div>
                </div>
            </div>
        </form>
))}
        </div>
    )
}

export default UpdateForm
